MARKET:
  symbol: MES
  type: futures

DATA:
  timeframe: '500T'
  lookback: 500

FEATURES:
  indicators:
    - ema
    - rsi
    - macd
    - VWMA
    - Accelerator Oscillator
    - Awesome Oscillator

LABELS:
  forward_bars: 10
  threshold: 0.05

MODEL:
  type: neural_network

TRADING:
  risk_management:
    stop_loss: 200
    take_profit: 500
  order_size: 2
